# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

aliases:
  - &filter-non-gh-pages
      branches:
        ignore:
          - gh-pages
  - &filter-only-master
      branches:
        only:
          - master
          - develop

version: 2
jobs:
  build:
    docker:
      - image: cimg/node:16.5
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install
          command: |
            sudo apt-get -y update
            yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          # relative to working_directory
          root: "./"
          paths:
            - "./"


  deploy:
     docker:
      - image: cimg/base:2021.04 
     steps:
       - add_ssh_keys:
           fingerprints:
           - e9:27:e2:e7:85:1e:6b:d8:c9:77:e7:e4:3e:9a:53:2b
           - SHA256:Qep1NK5/YrOlklfRsBnOHpgZOYrj4iCn2w++eMeq2pU
       - attach_workspace:
           at: "./"
       - run:
           name: Deploy Over SSH
           command: |
            ssh -p 65002 -o "StrictHostKeyChecking=no" u787324618@185.224.137.168
            cd domains/universaldot.me/public_html/test
            yarn build

  # deploy:
  #   docker:
  #     - image: cimg/node:14.16
  #   working_directory: ~/repo
  #   steps:
  #     - attach_workspace:
  #         at: ~/repo
  #     - run:
  #         name: Build & Deploy
  #         # added skip host key checking to avoid the manual prompt
  #         command: |
  #           mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
  #           git config --global user.email "devhub-deploy@users.noreply.github.com"
  #           git config --global user.name "Devhub Deployer"
  #           yarn build
  #           ssh -p 65002 u787324618@185.224.137.168

workflows:
  version: 2
  test_deploy:
    jobs:
      - build:
          filters: *filter-non-gh-pages
      - deploy:
          filters: *filter-only-master
          requires:
            - build
